version: '3.7'

services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "443:443"
        environment:
            - ENABLE_IPV6=true
        volumes:
            - ./certs:/etc/nginx/certs
            - ./custom_nginx_config.conf:/etc/nginx/conf.d/custom_nginx_config.conf
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - verloning-network
        restart: always

networks:
    verloning-network:
        external: true
